kind: Service
apiVersion: v1
metadata:
  name: globalgoapp-lbnodeport
  labels:
    app: globalgoapp-lbnodeport
spec:
  selector:
    app: globalgobackend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
    nodePort: 30045
  type: LoadBalancer