apiVersion: v1
kind: Service
metadata:
  name: globalnodeapp-nodeport
spec:
  type: NodePort
  selector:
    app: globalwebfe
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30049
    name: http80
    