apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: globalwebfe
  labels:
    app: globalwebfe
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: globalwebfe
  containers:
    - name: globalnodecontainer
      image: gcr.io/gcpdemoproject/globalsmallapp:master
      ports:
       - containerPort: 8080
      volumeMounts:
       - name: keymount
         mountPath: "/tmp"
         readOnly: true
      volumes:
       - name: keymount
        secret:
         secretName: thekey